---
layout: cv
title: Srikanth Gubbala's CV
---

# Srikanth Gubbala
**Brigham Young University - Idaho**

<div id="contact-info">
<a href="https://www.linkedin.com/in/srikanthgubbala/" target="_blank">LinkedIn</a>
</div>

---

## Currently
**Student, Brigham Young University - Idaho**

---

## Specialized In
- Data Visualization Analyst @ BYUI  
- Aspiring Business Intelligence Professional  
- Business Analyst  
- Power BI, SQL, Excel, DAX  
- Data Visualization, Leadership, Process Optimization  

---

## Interests
- Power Automate  
- Data Integration  
- Data Visualization  

---

## Education
**Bachelors of Science, Business Analytics**  
_Minor: Data Science_  
**Brigham Young University - Idaho**  
`2021 - 2025`

---

## Experience

### Data Visualization Analyst  
**Brigham Young University - Idaho**  
_Part-time_  
`October 2024 - Present`  
- Designed and implemented 20+ interactive dashboards using SQL, Power BI, and Azure Data Studio to provide data-driven insights for business decision-making.  
- Conducted data manipulation, regression analysis, and statistical modeling, improving process optimization by 30%.  
- Developed and automated Power Automate flows and Excel Macros, enhancing workflow efficiency and reducing manual work by 90%.  

---

### IT Service Desk Shift Lead  
**Brigham Young University - Idaho**  
_Part-time_  
`September 2023 - September 2024`  
- Led a team of 10 to troubleshoot IT issues at BYU-Idaho, emphasizing problem-solving and communication to ensure quick resolutions.  
- Assisted agents with phone calls and chat interactions by providing instructions and guidance to achieve optimal solutions for customer requests.  
- Supported the team in establishing goals and evaluating performance using quality assurance metrics and KPIs.  

---

<!-- ### Footer
Last updated: April 2025 -->